### ISSUE TITLE
Can you port all the ENS names to seed this service?

### ISSUE THREAD

**Issue by chandanworkacct** [findonflow/find#4]
Given all the buzz around ENS, these days may be this service should onboard all ENS domains automatically. It should be a very lightweight technical lift to get the public keys, create accounts with those keys, and add corresponding .fn domains to the registry. It will be a good buzz for the project as well as Flow.

**Comment by bjartek** [comment]
We will not do this. We have given the community the time to reserve names and we will reserve a list of names from flowverse.
